
// 0: job draft, 1 : job basic complete, 2 : job application complete, 3 : job published, 4 : job archieved, 5 : job deleted

export const JobState = [
  { label: 'Draft', value: 0 },
  { label: 'Basic Completed', value: 1 },
  { label: 'Form Completed', value: 2 },
  { label: 'Published', value: 3 },
  { label: 'Archieved', value: 4 },
  { label: 'Deleted', value: 5 }
]

export const JobApplication = [
  { label: 'Active', value: 0 },
  { label: 'Invited', value: 1 },
  { label: 'Applied', value: 2 },
  { label: 'Approved', value: 3 },
  { label: 'Rejected', value: 4 }
]

export const JobStage = [
  { label: 'Sourcing open', value: 0, color: 'primary' },
  { label: 'Contacted', value: 1, color: 'secondary' },
  { label: 'Written test', value: 2, color: 'info' },
  { label: 'Technical interview', value: 3, color: 'info' },
  { label: 'Culture fit round', value: 4, color: 'success' }
]

export const departmentList = [
  'Design',
  'Engineering',
  'Operations',
  'Sales & Marketing'
];

export const industryList = [
    "Accounting",
    "Airlines/Aviation",
    "Alternative Dispute Resolution",
    "Alternative Medicine",
    "Animation",
    "Apparel &amp; Fashion",
    "Architecture &amp; Planning",
    "Arts and Crafts",
    "Automotive",
    "Aviation &amp; Aerospace",
    "Banking",
    "Biotechnology",
    "Broadcast Media",
    "Building Materials",
    "Business Supplies and Equipment",
    "Capital Markets",
    "Chemicals",
    "Civic &amp; Social Organization",
    "Civil Engineering",
    "Commercial Real Estate",
    "Computer &amp; Network Security",
    "Computer Games",
    "Computer Hardware",
    "Computer Networking",
    "Computer Software",
    "Construction",
    "Consumer Electronics",
    "Consumer Goods",
    "Consumer Services",
    "Cosmetics",
    "Dairy",
    "Defense &amp; Space",
    "Design",
    "Education Management",
    "E-Learning",
    "Electrical/Electronic Manufacturing",
    "Entertainment",
    "Environmental Services",
    "Events Services",
    "Executive Office",
    "Facilities Services",
    "Farming",
    "Financial Services",
    "Fine Art",
    "Fishery",
    "Food &amp; Beverages",
    "Food Production",
    "Fund-Raising",
    "Furniture",
    "Gambling &amp; Casinos",
    "Glass, Ceramics &amp; Concrete",
    "Government Administration",
    "Government Relations",
    "Graphic Design",
    "Health, Wellness and Fitness",
    "Higher Education",
    "Hospital &amp; Health Care",
    "Hospitality",
    "Human Resources",
    "Import and Export",
    "Individual &amp; Family Services",
    "Industrial Automation",
    "Information Services",
    "Information Technology and Services",
    "Insurance",
    "International Affairs",
    "International Trade and Development",
    "Internet",
    "Investment Banking",
    "Investment Management",
    "Judiciary",
    "Law Enforcement",
    "Law Practice",
    "Legal Services",
    "Legislative Office",
    "Leisure, Travel &amp; Tourism",
    "Libraries",
    "Logistics and Supply Chain",
    "Luxury Goods &amp; Jewelry",
    "Machinery",
    "Management Consulting",
    "Maritime",
    "Marketing and Advertising",
    "Market Research",
    "Mechanical or Industrial Engineering",
    "Media Production",
    "Medical Devices",
    "Medical Practice",
    "Mental Health Care",
    "Military",
    "Mining &amp; Metals",
    "Motion Pictures and Film",
    "Museums and Institutions",
    "Music",
    "Nanotechnology",
    "Newspapers",
    "Nonprofit Organization Management",
    "Oil &amp; Energy",
    "Online Media",
    "Outsourcing/Offshoring",
    "Package/Freight Delivery",
    "Packaging and Containers",
    "Paper &amp; Forest Products",
    "Performing Arts",
    "Pharmaceuticals",
    "Philanthropy",
    "Photography",
    "Plastics",
    "Political Organization",
    "Primary/Secondary Education",
    "Printing",
    "Professional Training &amp; Coaching",
    "Program Development",
    "Public Policy",
    "Public Relations and Communications",
    "Public Safety",
    "Publishing",
    "Railroad Manufacture",
    "Ranching",
    "Real Estate",
    "Recreational Facilities and Services",
    "Religious Institutions",
    "Renewables &amp; Environment",
    "Research",
    "Restaurants",
    "Retail",
    "Security and Investigations",
    "Semiconductors",
    "Shipbuilding",
    "Sporting Goods",
    "Sports",
    "Staffing and Recruiting",
    "Supermarkets",
    "Telecommunications",
    "Textiles",
    "Think Tanks",
    "Tobacco",
    "Translation and Localization",
    "Transportation/Trucking/Railroad",
    "Utilities",
    "Venture Capital &amp; Private Equity",
    "Veterinary",
    "Warehousing",
    "Wholesale",
    "Wine and Spirits",
    "Wireless",
    "Writing and Editing"
];

export const functionList = [
  "Accounting/Auditing",
  "Administrative",
  "Advertising",
  "Business Analyst",
  "Financial Analyst",
  "Data Analyst",
  "Art/Creative",
  "Business Development",
  "Consulting",
  "Customer Service",
  "Distribution",
  "Design",
  "Education",
  "Engineering",
  "Finance",
  "General Business",
  "Health Care Provider",
  "Human Resources",
  "Information Technology",
  "Legal",
  "Management",
  "Manufacturing",
  "Marketing",
  "Other",
  "Public Relations",
  "Purchasing",
  "Product Management",
  "Project Management",
  "Production",
  "Quality Assurance",
  "Research",
  "Sales",
  "Science",
  "Strategy/Planning",
  "Supply Chain",
  "Training",
  "Writing/Editing"
];

export const empTypeList = [
  "Full-time",
  "Part-time",
  "Contract",
  "Temporary",
  "Other"
];

export const empExperienceList = [
  "Not Applicable",
  "Internship",
  "Entry level",
  "Associate",
  "Mid-Senior level",
  "Director",
  "Executive"
];

export const empEducationList = [
  "Unspecified",
  "High School or equivalent",
  "Certification",
  "Vocational",
  "Associate Degree",
  "Bachelor's Degree",
  "Master's Degree",
  "Doctorate",
  "Professional",
  "Some College Coursework Completed",
  "Vocational - HS Diploma",
  "Vocational - Degree",
  "Some High School Coursework"
];


export const currencyList = [
  "United States Dollar (USD)",
  "Euro (EUR)",
  "British Pound (GBP)",
  "Canadian Dollar (CAD)",
  "Australian Dollar (AUD)",
  "Indian Rupee (INR)",
  "United Arab Emirates Dirham (AED)",
  "Afghan Afghani (AFN)",
  "Albanian Lek (ALL)",
  "Armenian Dram (AMD)"
];

export const jobQuizTypeList = [
  { label: 'Paragraph', value: 'free-text', options: false },
  { label: 'Short answer', value: 'short_text', options: false },
  { label: 'Yes/No', value: 'boolean', options: false },
  { label: 'Dropdown', value: 'dropdown', options: true },
  { label: 'Multiple choice', value: 'multiple_choice', options: true },
  { label: 'Date', value: 'date', options: false },
  { label: 'Number', value: 'numeric', options: false },
  { label: 'File upload', value: 'file', options: false }
];

export const countryList = [
  "United States",
  "United Kingdom",
  "France",
  "India",
  "Germany",
  "Australia",
  "Canada",

  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia, Plurinational State of",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, The Democratic Republic of the",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran, Islamic Republic of",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, Democratic People's Republic of",
  "Korea, Republic of",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States of",
  "Moldova, Republic of",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "North Macedonia",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela, Bolivarian Republic of",
  "Vietnam",
  "Virgin Islands, British",
  "Virgin Islands, U.S.",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands"
];


