export const skillList = [
  'A/B Testing',
  'Adobe Illustrator',
  'Adobe Photoshop',
  'Adobe XD',
  'Amazon API',
  'Amazon SEO',
  'Android',
  'Angular',
  'Animators',
  'AnyLogic',
  'Apache Spark',
  'API Integration',
  'AppleScript',
  'ArcGIS',
  'Arduino',
  'ARKit',
  'Artificial Intelligence',
  'Asana',
  'Augmented Reality',
  'AWS',

  'Back-End',
  'BigCommerce',
  'Blockchain',
  'Bluetooth',
  'Bootstrap',
  'BuddyPress',
  'Business Valuation',

  'CakePHP',
  'Camera',
  'Chatbot',
  'Chrome Extension',
  'Cisco ASA',
  'Cisco Meraki',
  'ClickFunnels',
  'Cocos2d',
  'CodeIgniter',
  'Cognos',
  'Conversion Rate Optimizer',
  'CouchDB',
  'C++',
  'C',
  'Craft CMS',
  'CRM',
  'Cryptocurrency',
  'Crystal Reports',
  'C#',
  'CSS',

  'd3.js',
  'Data Analysts',
  'Database',
  'Data Entry',
  'Data Extraction',
  'Data Mining',
  'Data Visualization',
  'Delphi',
  'Desktop Applications',
  'Django',
  'DNS',
  'Domo',
  'Drupal',

  'Ecommerce',
  'Elasticsearch',
  'Elementor',
  'Embedded C',
  'Embedded Linux',
  'Erlang',
  'ESP32',
  'Ethereum',
  'Excel VBA',
  'Explainer Video',
  'Expression Engine',
  'Excel',

  'Fabric.js',
  'Figma',
  'Filemaker',
  'Firebase',
  'Flask',
  'Flutter',
  'Forex',
  'Full Stack',

  'Gatsby',
  'GoDaddy',
  'Golang',
  'Google Analytics',
  'Google Apps',
  'Google Apps Script',
  'Google Cloud Platform',
  'Google Data Studio',
  'Google Docs',
  'Google Tag Manager',
  'Graphic',
  'Gravity Forms',
  'Groovy',
  'Growth',

  'HTML5',
  'HTML',
  'HubSpot',

  'IBM SPSS',
  'Internet of Things',
  'Invision',
  'Ionic Framework',

  'Java',
  'JavaScript',
  'Joomla',
  'JSON',

  'Kajabi',
  'Kentico CMS',
  'Kibana',

  'Landing Pages',
  'Laravel',
  'LeadPages',
  'LearnDash',
  'Linear Regression',
  'Lua',

  '3ds Max',
  'Machine Learning',
  'Magento',
  'ManyChat',
  'Mapbox',
  'Marketo',
  'Market',
  'MATLAB',
  'MetaTrader 4 (MT4)',
  'Microcontroller',
  'Microsoft Access',
  'Microsoft Dynamics Administration',
  'Microsoft Exchange Server',
  'Microsoft Power BI',
  'Microsoft Project',
  'Microsoft Windows Server',
  'Mockup',
  'Moodle',
  'MySQL',
  'Microsoft Windows Azure',

  'Natural Language Processing',
  'NetSuite',
  'Network',
  'Next.js',
  'Nginx',
  'NinjaTrader',
  'NopCommerce',

  'OCR Tesseract',
  'Offshore',
  'OpenCart',
  'OpenCV',

  'Phaser',
  'PHP',
  'PrestaShop',
  'Product Designe',
  'Product Development',
  'Project Manage',
  'Project Schedule',
  'Puppet',
  'Python',

  'Qlikview',
  'Qt',
  'Qualitative Research',

  'Rapid Miner',
  'Raspberry Pi',
  'React.js',
  'React Native',
  'Recruiters & Recruitment',
  'Robotic Process Automation',
  'R',
  'Ruby',
  'Ruby on Rails',

  'SketchUp',
  'Salesforce Apex',
  'Salesforce',
  'SAS',
  'Scrapy',
  'Scripting',
  'SEO',
  'Sharetribe',
  'Shopify',
  'Sketch',
  'Slider Revolution',
  'Spring Boot',
  'SQL',
  'SquareSpace',
  'SSL Specialists',
  'Stata Specialists',
  'Statistics Tutors',
  'Statistics Specialists',
  'Stm32',
  'Stripe',
  'Survey',

  'Telerik Sitefinity CMS',
  'Tableau Software',
  'TensorFlow',
  'Terraform',
  'Three.js',
  'Thrive Themes',
  'Trello',
  'Twilio API',

  'Ubiquiti',
  'Unbounce',

  'VB.NET',
  'VBScript',
  'VBulletin',
  'Virtual Reality',
  'Visme',
  'VMWare',
  'Vue.js',

  'Windows PowerShell',
  'Web Crawling',
  'Web Designe',
  'Web Development',
  'Webflow',
  'WebGL',
  'WebRTC',
  'Web Scraping',
  'Web Testing',
  'Weebly',
  'Weka',
  'Windows',
  'Wireframing',
  'WiX',
  'Woocommerce',
  'WordPress',
  'Wordpress Plugin',
  'WPLMS',

  'Xamarin',
  'XML',

  'Yoast SEO',

  'Zabbix',
  'Zapier',
  'Zeplin'


]
